### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gwlove**
- edited copy
- added image

### CODE REVIEW

**Review by matejko0077 — APPROVED** [review]

**Comment by Mandog1120** [comment]
4637ea57d0ac7005b15b1e43cc2da850460aee99

**Comment by Mandog1120** [comment]
4637ea57d0ac7005b15b1e43cc2da850460aee99

**Comment by Mandog1120** [comment]
47e0b14495688699d71aa35d619c0ecfd60a951b

**Comment by Mandog1120** [comment]
1411c3f804d9888d676a0c585cb785d5ea09a6f3

**Pull request merged**
